services:
  renotes:
    image: renotes/renotes
    container_name: renotes
    restart: unless-stopped
    ports:
      - 3030:3030
    volumes:
      - /directory/to/data:/data
      # Change the renotes directory to where you want to keep your data
    environment:
      - RENOTES_USERNAME= #username (default is renotes)
      - RENOTES_PASSWORD=password #password (default is password)
      - AUTH_SECRET= #SECRET KEY HERE
      - PUID=1000
      - PGID=1000
