services:
  renotes:
    image: docker_image
    container_name: renotes
    restart: unless-stopped
    ports:
      - 3030:3030
    volumes:
      - ${directory_for_your_notes}:/data
    environment:
      - PUID=1000
      - PGID=1000
