services:
  renotes:
    image: renotes/renotes
    container_name: renotes
    restart: unless-stopped
    ports:
      - 3030:3030
    volumes:
      - ${RENOTES_DIRECTORY}:/data
      # Change the renotes directory to where you want to keep your data
    environment:
      - PUID=1000
      - PGID=1000
